version: "3"
services:
  staged:
    image: us.gcr.io/${GCP_PROJECT}/view-store.${DOMAIN}.${ID}:latest
    container_name: staged
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      NODE_ENV: staging
      NETWORK:
      SERVICE:
      DOMAIN:
      ID:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
      MONGODB_USER: gcp-staging
      MONGODB_HOST: staging-ggjlv.gcp.mongodb.net

networks:
  default:
    external:
      name: cloudbuild
